theme="material-design"
baseurl = "http://blog.insanet.eu/"
languageCode = "en-us"
title = "Insanet Blog"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
# disqusShortname = "Your Disqus Name" # optional
copyright = "© 2017 Insanet"
publishDir = "docs"

[params]
  author = "Czarnodziej"
  # description = "Your Site Description" # optional
  twitter = "Czarnodziej" # optional
  # gitlab = "Your Gitlab Name" # optional
  github = "Czarnodziej" # optional
  # facebook = "Your facebook Name" # optional
  # gplus = "Your Google+ profile name" # optional
  linkedin = "marcin-mongia%C5%82o-4a083457" # optional
  # headerCover = "images/headerCover.png" # optional
  # footerCover = "images/footerCover.png" # optional
  # googleAnalyticsUserID = "Your Analytics User Id" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
